[versions]

agp = "8.13.2"

composeVersion = "1.10.0"

converterGson = "3.0.0"
datastorePreferences = "1.2.0"
datastorePreferencesCore = "1.2.0"
kotlin = "2.3.0"

coreKtx = "1.17.0"

junit = "4.13.2"

#junitVersion = "1.3.0"

#espressoCore = "3.7.0"

kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.10.0"

activityCompose = "1.12.1"

composeBom = "2025.12.00"

navigationCompose = "2.9.6"

material3 = "1.4.0"

navigationRuntimeKtx = "2.9.6"

navigationTesting = "2.9.6"

retrofit = "3.0.0"
robolectric = "4.16"

roomVersion = "2.8.4"

coreKtxVersion = "1.7.0"

ui = "1.10.0"
#uiToolingPreview = "1.10.0"
#uiTooling = "1.10.0"




[libraries]

androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }

androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeVersion" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferencesCore" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }

androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }

androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomVersion" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

#androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

#androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }

androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationTesting" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
#androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
#androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }



[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }